BEGIN;
CREATE TABLE IF NOT EXISTS artifact_metadata (organization_id text NOT NULL,workspace_id text NOT NULL,assessment_id text NOT NULL,storage_artifact_id text NOT NULL,parser_artifact_id text NOT NULL,original_name text NOT NULL,media_type text NOT NULL,size_bytes bigint NOT NULL CHECK (size_bytes >= 0),checksum_sha256 text NOT NULL,parser text NOT NULL,warnings_json jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL,PRIMARY KEY (workspace_id,assessment_id,storage_artifact_id),FOREIGN KEY (workspace_id,assessment_id) REFERENCES assessments(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS artifact_metadata_scope_idx ON artifact_metadata (organization_id,workspace_id,assessment_id,created_at);
CREATE TABLE IF NOT EXISTS source_segments (organization_id text NOT NULL,workspace_id text NOT NULL,assessment_id text NOT NULL,parser_artifact_id text NOT NULL,segment_id text NOT NULL,ordinal integer NOT NULL CHECK (ordinal >= 0),kind text NOT NULL,locator_json jsonb NOT NULL,content text NOT NULL,content_sha256 text NOT NULL,title text,PRIMARY KEY (workspace_id,assessment_id,segment_id),FOREIGN KEY (workspace_id,assessment_id) REFERENCES assessments(workspace_id,id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS source_segments_scope_idx ON source_segments (organization_id,workspace_id,assessment_id,parser_artifact_id,ordinal);
CREATE TABLE IF NOT EXISTS extraction_snapshots (organization_id text NOT NULL,workspace_id text NOT NULL,assessment_id text NOT NULL,schema_version text NOT NULL,provider text NOT NULL,prompt_version text NOT NULL,status text NOT NULL,payload_json jsonb NOT NULL,persisted_at timestamptz NOT NULL,PRIMARY KEY (workspace_id,assessment_id),FOREIGN KEY (workspace_id,assessment_id) REFERENCES assessments(workspace_id,id) ON DELETE CASCADE);
ALTER TABLE artifact_metadata ENABLE ROW LEVEL SECURITY; ALTER TABLE source_segments ENABLE ROW LEVEL SECURITY; ALTER TABLE extraction_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE artifact_metadata FORCE ROW LEVEL SECURITY; ALTER TABLE source_segments FORCE ROW LEVEL SECURITY; ALTER TABLE extraction_snapshots FORCE ROW LEVEL SECURITY;
CREATE POLICY artifact_metadata_member_read ON artifact_metadata FOR SELECT TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,NULL));
CREATE POLICY source_segments_member_read ON source_segments FOR SELECT TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,NULL));
CREATE POLICY extraction_snapshots_member_read ON extraction_snapshots FOR SELECT TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,NULL));
CREATE POLICY artifact_metadata_editor_write ON artifact_metadata FOR ALL TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin'])) WITH CHECK (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin']));
CREATE POLICY source_segments_editor_write ON source_segments FOR ALL TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin'])) WITH CHECK (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin']));
CREATE POLICY extraction_snapshots_editor_write ON extraction_snapshots FOR ALL TO authenticated USING (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin'])) WITH CHECK (app_supabase_has_membership(organization_id,workspace_id,ARRAY['editor','admin']));
CREATE OR REPLACE FUNCTION replace_processing_snapshot(p_organization_id text,p_workspace_id text,p_assessment_id text,p_artifacts jsonb,p_segments jsonb,p_extraction jsonb,p_persisted_at timestamptz) RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path=public,pg_temp AS $$
BEGIN
IF NOT app_supabase_has_membership(p_organization_id,p_workspace_id,ARRAY['editor','admin']) THEN RAISE EXCEPTION 'workspace membership denied' USING ERRCODE='42501'; END IF;
IF NOT EXISTS (SELECT 1 FROM assessments a WHERE a.organization_id=p_organization_id AND a.workspace_id=p_workspace_id AND a.id=p_assessment_id) THEN RAISE EXCEPTION 'assessment not found' USING ERRCODE='P0002'; END IF;
DELETE FROM source_segments WHERE organization_id=p_organization_id AND workspace_id=p_workspace_id AND assessment_id=p_assessment_id; DELETE FROM artifact_metadata WHERE organization_id=p_organization_id AND workspace_id=p_workspace_id AND assessment_id=p_assessment_id; DELETE FROM extraction_snapshots WHERE organization_id=p_organization_id AND workspace_id=p_workspace_id AND assessment_id=p_assessment_id;
INSERT INTO artifact_metadata SELECT p_organization_id,p_workspace_id,p_assessment_id,x.storage_artifact_id,x.parser_artifact_id,x.original_name,x.media_type,x.size_bytes,x.checksum_sha256,x.parser,x.warnings_json,x.created_at FROM jsonb_to_recordset(p_artifacts) AS x(storage_artifact_id text,parser_artifact_id text,original_name text,media_type text,size_bytes bigint,checksum_sha256 text,parser text,warnings_json jsonb,created_at timestamptz);
INSERT INTO source_segments SELECT p_organization_id,p_workspace_id,p_assessment_id,x.parser_artifact_id,x.segment_id,x.ordinal,x.kind,x.locator_json,x.content,x.content_sha256,x.title FROM jsonb_to_recordset(p_segments) AS x(parser_artifact_id text,segment_id text,ordinal integer,kind text,locator_json jsonb,content text,content_sha256 text,title text);
INSERT INTO extraction_snapshots (organization_id,workspace_id,assessment_id,schema_version,provider,prompt_version,status,payload_json,persisted_at) VALUES (p_organization_id,p_workspace_id,p_assessment_id,p_extraction->>'schemaVersion',p_extraction->>'provider',p_extraction->>'promptVersion',p_extraction->>'status',p_extraction,p_persisted_at);
END; $$;
REVOKE ALL ON FUNCTION replace_processing_snapshot(text,text,text,jsonb,jsonb,jsonb,timestamptz) FROM PUBLIC; GRANT EXECUTE ON FUNCTION replace_processing_snapshot(text,text,text,jsonb,jsonb,jsonb,timestamptz) TO authenticated;
COMMIT;
