import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SupabasePostgresStore } from "../lib/supabase-postgres.ts";
const config={projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test_1234567890",timeoutMs:1000};const scope={organizationId:"org-a",workspaceId:"workspace-a"};const extraction={schemaVersion:"1.0",provider:"local-deterministic-v1",promptVersion:"platform-extraction-v1",status:"complete",objects:[],warnings:[],stats:{objectCount:0,evidenceReferenceCount:0}};const snapshot={assessmentId:"assessment-a",artifacts:[{storageArtifactId:"stored-a",parserArtifactId:"parsed-a",originalName:"architecture.md",mediaType:"text/markdown",size:12,checksumSha256:"abc",parser:"text",warnings:[],createdAt:"2026-09-19T00:00:00.000Z"}],parsedArtifacts:[{artifactId:"parsed-a",artifactName:"architecture.md",parser:"text",sourceSegments:[{id:"seg-a",artifactId:"parsed-a",artifactName:"architecture.md",ordinal:0,kind:"text",locator:{lineStart:1,lineEnd:1},content:"CRM owns Customer",contentSha256:"def"}],warnings:[],stats:{segmentCount:1,characterCount:17}}],extraction,persistedAt:"2026-09-19T00:00:01.000Z"};function response(json,status=200){return new Response(json===null?null:JSON.stringify(json),{status,headers:{"Content-Type":"application/json"}});}
test("managed processing replacement is one authenticated tenant-scoped RPC",async()=>{let call;const store=new SupabasePostgresStore(config,async(url,init)=>{call={url:String(url),init};return response(null,204);});const saved=await store.replaceProcessing("user-jwt",scope,snapshot);assert.match(call.url,/\/rest\/v1\/rpc\/replace_processing_snapshot$/);const body=JSON.parse(call.init.body);assert.equal(body.p_organization_id,"org-a");assert.equal(body.p_workspace_id,"workspace-a");assert.equal(body.p_assessment_id,"assessment-a");assert.equal(body.p_segments[0].segment_id,"seg-a");assert.equal(call.init.headers.Authorization,"Bearer user-jwt");assert.equal(saved.persistedAt,snapshot.persistedAt);});
test("managed processing reads are tenant filtered and reconstruct evidence",async()=>{const calls=[];const store=new SupabasePostgresStore(config,async(url)=>{const u=String(url);calls.push(u);if(u.includes("extraction_snapshots?"))return response([{payload_json:extraction,persisted_at:snapshot.persistedAt}]);if(u.includes("artifact_metadata?"))return response([{storage_artifact_id:"stored-a",parser_artifact_id:"parsed-a",original_name:"architecture.md",media_type:"text/markdown",size_bytes:12,checksum_sha256:"abc",parser:"text",warnings_json:[],created_at:"2026-09-19T00:00:00.000Z"}]);return response([{parser_artifact_id:"parsed-a",segment_id:"seg-a",ordinal:0,kind:"text",locator_json:{lineStart:1,lineEnd:1},content:"CRM owns Customer",content_sha256:"def",title:null}]);});const found=await store.findProcessing("user-jwt",scope,"assessment-a");assert.equal(found.parsedArtifacts[0].sourceSegments[0].content,"CRM owns Customer");assert.ok(calls.every((u)=>u.includes("organization_id=eq.org-a")&&u.includes("workspace_id=eq.workspace-a")&&u.includes("assessment_id=eq.assessment-a")));});
test("processing migration enforces membership RLS and invoker RPC",()=>{const sql=fs.readFileSync(new URL("../db/migrations/003_processing_rls.sql",import.meta.url),"utf8");assert.match(sql,/ENABLE ROW LEVEL SECURITY/g);assert.match(sql,/FORCE ROW LEVEL SECURITY/g);assert.match(sql,/app_supabase_has_membership/);assert.match(sql,/ARRAY\['editor','admin'\]/);assert.match(sql,/SECURITY INVOKER/);assert.doesNotMatch(sql,/service_role/i);});
test("managed processing selection is request scoped",()=>{const source=fs.readFileSync(new URL("../lib/server-processing-access.ts",import.meta.url),"utf8");assert.match(source,/PERSISTENCE_CONFIG\.provider === "supabase-postgres"/);assert.match(source,/extractAccessToken\(request\)/);assert.match(source,/store\.replaceProcessing/);assert.match(source,/store\.findProcessing/);});
