import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SupabaseReportHistoryStore } from "../lib/supabase-report-history.ts";
const config={projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test",timeoutMs:1000}; const scope={organizationId:"org-a",workspaceId:"workspace-a"};
const report={assessmentId:"assessment-a",title:"Diagnostic",generatedFromDiagnosticAt:"2026-09-22T00:00:00.000Z"};
const snapshot={schemaVersion:"1.0",id:"report_assessment-a_v1",assessmentId:"assessment-a",version:1,versionLabel:"v1",createdAt:"2026-09-22T00:01:00.000Z",generatedFromDiagnosticAt:report.generatedFromDiagnosticAt,report};
function response(json,status=200){return new Response(JSON.stringify(json),{status,headers:{"Content-Type":"application/json"}});}
test("managed report history read is JWT-authenticated and tenant-filtered",async()=>{const calls=[];const store=new SupabaseReportHistoryStore(config,async(url,init)=>{calls.push({url:String(url),init});return response([{snapshot_json:snapshot}]);});const history=await store.list("jwt",scope,"assessment-a");assert.equal(history.length,1);assert.match(calls[0].url,/organization_id=eq\.org-a/);assert.match(calls[0].url,/workspace_id=eq\.workspace-a/);assert.match(calls[0].url,/assessment_id=eq\.assessment-a/);assert.equal(calls[0].init.headers.Authorization,"Bearer jwt");});
test("managed report save delegates version allocation to atomic RPC",async()=>{let call;const store=new SupabaseReportHistoryStore(config,async(url,init)=>{call={url:String(url),init};return response({snapshot_json:snapshot});});const saved=await store.save("jwt",scope,report,"2026-09-22T00:01:00.000Z");const body=JSON.parse(call.init.body);assert.match(call.url,/rpc\/save_report_snapshot$/);assert.equal(body.p_organization_id,"org-a");assert.equal(body.p_workspace_id,"workspace-a");assert.equal(body.p_assessment_id,"assessment-a");assert.equal(body.p_report.generatedFromDiagnosticAt,report.generatedFromDiagnosticAt);assert.equal(saved.version,1);});
test("managed report lookup scopes report ID to tenant and assessment",async()=>{let url="";const store=new SupabaseReportHistoryStore(config,async(input)=>{url=String(input);return response([{snapshot_json:snapshot}]);});const found=await store.findById("jwt",scope,"assessment-a",snapshot.id);assert.equal(found.id,snapshot.id);assert.match(url,/report_id=eq\.report_assessment-a_v1/);assert.match(url,/workspace_id=eq\.workspace-a/);});
test("report-history migration forces RLS and binds save to completed current findings",()=>{const sql=fs.readFileSync(new URL("../db/migrations/006_report_history_rls.sql",import.meta.url),"utf8");assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/ARRAY\['editor','admin'\]/);assert.match(sql,/SECURITY INVOKER/);assert.match(sql,/finding_reviews/);assert.match(sql,/reviewedAt/);assert.match(sql,/generatedFromDiagnosticAt/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/UNIQUE \(workspace_id,assessment_id,version\)/);assert.doesNotMatch(sql,/service_role/);});
