import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { createFindingReview, setFindingDecision, completeFindingReview } from "../lib/finding-review.ts";
import { diagnosticFingerprint, StaleFindingReviewError } from "../lib/finding-review-persistence.ts";
import { SupabaseFindingReviewStore } from "../lib/supabase-finding-review.ts";
const config={projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test",timeoutMs:1000}; const scope={organizationId:"org-a",workspaceId:"workspace-a"};
const evidence={segmentId:"seg-a",artifactId:"art-a",artifactName:"a.md",locator:"lines 1-2",evidenceType:"direct"};
const finding={id:"f-a",ruleId:"r",ruleVersion:"1",category:"entity_identity",severity:"high",confidence:1,factStatus:"derived",title:"Fragmented ID",description:"d",businessImpact:"b",technicalImpact:"t",affectedObjectIds:["obj-a"],evidence:[evidence],recommendation:"r",validationQuestions:[],reviewStatus:"pending"};
const diagnostics={schemaVersion:"1.0",assessmentId:"assessment-a",generatedAt:"2026-09-21T00:00:00.000Z",extractionApprovedAt:"2026-09-20T00:00:00.000Z",engineVersion:"1",findings:[finding],summary:{findingCount:1,high:1,medium:0,low:0}};
const extractionReview={schemaVersion:"1.0",approved:true,approvedAt:"2026-09-20T00:00:00.000Z",objects:[]};
function response(json,status=200){return new Response(JSON.stringify(json),{status,headers:{"Content-Type":"application/json"}});}
test("managed finding review read is JWT-authenticated and tenant-filtered",async()=>{const calls=[];const review=createFindingReview(diagnostics);const store=new SupabaseFindingReviewStore(config,async(url,init)=>{calls.push({url:String(url),init});return response([{diagnostic_fingerprint:diagnosticFingerprint(diagnostics),diagnostics_json:diagnostics,review_json:review,accepted_findings_json:[],updated_at:"2026-09-21T00:00:00.000Z"}]);});const found=await store.find("jwt",scope,"assessment-a",diagnostics);assert.equal(found.stale,false);assert.match(calls[0].url,/organization_id=eq\.org-a/);assert.match(calls[0].url,/workspace_id=eq\.workspace-a/);assert.equal(calls[0].init.headers.Authorization,"Bearer jwt");});
test("managed finding review atomically persists accepted materialization against exact extraction review",async()=>{let call;let review=createFindingReview(diagnostics);review=setFindingDecision(review,"f-a","accepted");review=completeFindingReview(review,"2026-09-21T00:01:00.000Z");const store=new SupabaseFindingReviewStore(config,async(url,init)=>{call={url:String(url),init};return new Response(null,{status:204});});const saved=await store.save("jwt",scope,"assessment-a",diagnostics,review,diagnosticFingerprint(diagnostics),extractionReview);const body=JSON.parse(call.init.body);assert.match(call.url,/rpc\/save_finding_review$/);assert.deepEqual(body.p_expected_extraction_review,extractionReview);assert.equal(body.p_accepted_findings.length,1);assert.equal(saved.acceptedFindings[0].reviewStatus,"accepted");});
test("managed finding review rejects stale client fingerprint before network",async()=>{let called=false;const store=new SupabaseFindingReviewStore(config,async()=>{called=true;return response([]);});await assert.rejects(()=>store.save("jwt",scope,"assessment-a",diagnostics,createFindingReview(diagnostics),"0".repeat(64),extractionReview),StaleFindingReviewError);assert.equal(called,false);});
test("finding-review migration forces RLS, editor writes, and extraction-approval staleness checks",()=>{const sql=fs.readFileSync(new URL("../db/migrations/005_finding_review_rls.sql",import.meta.url),"utf8");assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/app_supabase_has_membership\(organization_id,workspace_id,NULL\)/);assert.match(sql,/ARRAY\['editor','admin'\]/);assert.match(sql,/current_review <> p_expected_extraction_review/);assert.match(sql,/extractionApprovedAt/);assert.match(sql,/accepted_findings_json/);assert.match(sql,/SECURITY INVOKER/);assert.doesNotMatch(sql,/service_role/);});
