import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { createAssessmentDraft } from "../lib/assessment.ts";
import { SupabasePostgresStore, SupabasePersistenceError } from "../lib/supabase-postgres.ts";
const config = { projectUrl: "https://example.supabase.co", publishableKey: "sb_publishable_test_1234567890", timeoutMs: 1000 };
const scope = { organizationId: "org-a", workspaceId: "workspace-a" };
const assessment = createAssessmentDraft({ companyName: "Acme", assessmentTitle: "Identity", industry: "Tech", focusArea: "entity-identifier-fragmentation", primaryEntity: "Customer", knownSystems: "CRM", businessConcern: "IDs differ", reportAudience: "CTO", limitsAcknowledged: true });
function response(json, status = 200) { return new Response(JSON.stringify(json), { status, headers: { "Content-Type": "application/json" } }); }
test("managed assessment reads are JWT-authenticated and explicitly tenant-filtered", async () => { const calls = []; const store = new SupabasePostgresStore(config, async (url, init) => { calls.push({ url: String(url), init }); return response([{ payload_json: assessment }]); }); const found = await store.findAssessment("user-jwt", scope, assessment.id); assert.equal(found.id, assessment.id); assert.match(calls[0].url, /organization_id=eq\.org-a/); assert.match(calls[0].url, /workspace_id=eq\.workspace-a/); assert.equal(calls[0].init.headers.Authorization, "Bearer user-jwt"); assert.equal(calls[0].init.headers.apikey, config.publishableKey); assert.equal(calls[0].init.cache, "no-store"); });
test("managed assessment creation sends server-derived scope and no privileged service key", async () => { let call; const store = new SupabasePostgresStore(config, async (url, init) => { call = { url: String(url), init }; return new Response(null, { status: 201 }); }); await store.createAssessment("user-jwt", scope, assessment); const body = JSON.parse(call.init.body); assert.deepEqual({ organization_id: body.organization_id, workspace_id: body.workspace_id }, { organization_id: "org-a", workspace_id: "workspace-a" }); assert.equal(call.init.headers.Authorization, "Bearer user-jwt"); assert.equal(call.init.headers.apikey, config.publishableKey); });
test("membership resolution requires exact user, organization, and workspace", async () => { const calls = []; const store = new SupabasePostgresStore(config, async (url) => { calls.push(String(url)); if (String(url).includes("memberships?")) return response([{ user_id: "user-a", organization_id: "org-a", workspace_id: "workspace-a", role: "editor", created_at: "2026-09-18T00:00:00.000Z" }]); return response([{ id: "workspace-a", name: "Workspace A", organization_id: "org-a", created_at: "2026-09-18T00:00:00.000Z", organizations: { id: "org-a", name: "Org A", created_at: "2026-09-18T00:00:00.000Z" } }]); }); const resolved = await store.resolveMembership("user-jwt", "user-a", scope); assert.equal(resolved.membership.role, "editor"); assert.ok(calls[0].includes("user_id=eq.user-a") && calls[0].includes("organization_id=eq.org-a") && calls[0].includes("workspace_id=eq.workspace-a")); });
test("managed persistence fails closed without a user JWT or on provider failure", async () => { const store = new SupabasePostgresStore(config, async () => response({ message: "denied" }, 403)); await assert.rejects(() => store.findAssessment("", scope, assessment.id), SupabasePersistenceError); await assert.rejects(() => store.findAssessment("jwt", scope, assessment.id), /status 403/); });
test("Supabase migration binds tenant access to auth.uid membership and editor/admin insert", () => { const migration = fs.readFileSync(new URL("../db/migrations/002_supabase_jwt_rls.sql", import.meta.url), "utf8"); assert.match(migration, /auth\.uid\(\)::text/); assert.match(migration, /memberships_supabase_self_read/); assert.match(migration, /assessments_supabase_member_read/); assert.match(migration, /ARRAY\['editor','admin'\]/); assert.doesNotMatch(migration, /service_role/); });
