import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SupabaseGeneratedReportMetadataStore } from "../lib/supabase-generated-report-metadata.ts";
const config={projectUrl:"https://example.supabase.co",publishableKey:"sb_publishable_test",timeoutMs:1000}; const scope={organizationId:"org-a",workspaceId:"workspace-a"};
const stored={reportId:"report-a",assessmentId:"assessment-a",version:1,storageKey:"org-a/workspace-a/assessment-a/random.pdf",checksumSha256:"a".repeat(64),mediaType:"application/pdf",size:100,pageCount:2,createdAt:"2026-09-24T00:00:00.000Z"};
const row={report_id:stored.reportId,assessment_id:stored.assessmentId,version:stored.version,storage_key:stored.storageKey,checksum_sha256:stored.checksumSha256,media_type:stored.mediaType,size_bytes:stored.size,page_count:stored.pageCount,created_at:stored.createdAt};
function response(json,status=200){return new Response(JSON.stringify(json),{status,headers:{"Content-Type":"application/json"}});}
test("managed generated report lookup is JWT-authenticated and tenant-filtered",async()=>{let call;const store=new SupabaseGeneratedReportMetadataStore(config,async(url,init)=>{call={url:String(url),init};return response([row]);});const found=await store.find(scope,"assessment-a","report-a","jwt");assert.equal(found.reportId,"report-a");assert.match(call.url,/organization_id=eq\.org-a/);assert.match(call.url,/workspace_id=eq\.workspace-a/);assert.match(call.url,/assessment_id=eq\.assessment-a/);assert.match(call.url,/report_id=eq\.report-a/);assert.equal(call.init.headers.Authorization,"Bearer jwt");});
test("managed generated report insert derives tenant scope server-side",async()=>{let call;const store=new SupabaseGeneratedReportMetadataStore(config,async(url,init)=>{call={url:String(url),init};return response([row]);});const saved=await store.save(scope,stored,"jwt");const body=JSON.parse(call.init.body);assert.equal(body.organization_id,"org-a");assert.equal(body.workspace_id,"workspace-a");assert.equal(body.assessment_id,"assessment-a");assert.equal(saved.checksumSha256,stored.checksumSha256);assert.equal(call.init.headers.Authorization,"Bearer jwt");});
test("managed generated report metadata fails closed without verified token",async()=>{const store=new SupabaseGeneratedReportMetadataStore(config,async()=>response([]));await assert.rejects(()=>store.find(scope,"assessment-a","report-a"),/verified Supabase access token/);});
test("generated report metadata migration forces RLS and editor-admin writes",()=>{const sql=fs.readFileSync(new URL("../db/migrations/007_generated_report_objects_rls.sql",import.meta.url),"utf8");assert.match(sql,/force row level security/i);assert.match(sql,/auth\.uid\(\)/);assert.match(sql,/editor','admin/);assert.doesNotMatch(sql,/service_role/);});
