import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { createExtractionReview, setReviewStatus, approveExtraction } from "../lib/extraction-review.ts";
import { extractionFingerprint, StaleExtractionReviewError } from "../lib/review-persistence.ts";
import { SupabaseExtractionReviewStore } from "../lib/supabase-extraction-review.ts";
const config = { projectUrl: "https://example.supabase.co", publishableKey: "sb_publishable_test", timeoutMs: 1000 }; const scope = { organizationId: "org-a", workspaceId: "workspace-a" }; const object = { id: "obj-a", kind: "system", name: "CRM", normalizedName: "crm", confidence: 1, extractionMethod: "demo", evidence: [{ segmentId: "seg-a", artifactId: "art-a", artifactName: "a.md", locator: "lines 1-2", evidenceType: "direct" }], attributes: {} }; const extraction = { schemaVersion: "1.0", provider: "local-deterministic", promptVersion: "v1", status: "ready", objects: [object], warnings: [], stats: { objectCount: 1, evidenceReferenceCount: 1 } }; function response(json,status=200){return new Response(JSON.stringify(json),{status,headers:{"Content-Type":"application/json"}});}
test("managed review read is JWT-authenticated and explicitly tenant-filtered", async()=>{const calls=[];const review=createExtractionReview(extraction.objects);const store=new SupabaseExtractionReviewStore(config,async(url,init)=>{calls.push({url:String(url),init});return response([{extraction_fingerprint:extractionFingerprint(extraction),review_json:review,updated_at:"2026-09-20T00:00:00.000Z"}]);});const found=await store.find("jwt",scope,"assessment-a",extraction);assert.equal(found.stale,false);assert.match(calls[0].url,/organization_id=eq\.org-a/);assert.match(calls[0].url,/workspace_id=eq\.workspace-a/);assert.equal(calls[0].init.headers.Authorization,"Bearer jwt");});
test("managed review save sends exact extraction boundary to atomic RPC",async()=>{let call;let review=createExtractionReview(extraction.objects);review=setReviewStatus(review,"obj-a","confirmed");review=approveExtraction(review,"2026-09-20T00:00:00.000Z");const store=new SupabaseExtractionReviewStore(config,async(url,init)=>{call={url:String(url),init};return new Response(null,{status:204});});await store.save("jwt",scope,"assessment-a",extraction,review,extractionFingerprint(extraction));const body=JSON.parse(call.init.body);assert.match(call.url,/rpc\/save_extraction_review$/);assert.deepEqual(body.p_expected_extraction,extraction);assert.equal(body.p_organization_id,"org-a");assert.equal(body.p_workspace_id,"workspace-a");});
test("managed review save fails before network on stale client fingerprint",async()=>{let called=false;const store=new SupabaseExtractionReviewStore(config,async()=>{called=true;return response([]);});await assert.rejects(()=>store.save("jwt",scope,"assessment-a",extraction,createExtractionReview(extraction.objects),"0".repeat(64)),StaleExtractionReviewError);assert.equal(called,false);});
test("migration enforces RLS and database-side extraction staleness check",()=>{const sql=fs.readFileSync(new URL("../db/migrations/004_extraction_review_rls.sql",import.meta.url),"utf8");assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/app_supabase_has_membership\(organization_id,workspace_id,NULL\)/);assert.match(sql,/ARRAY\['editor','admin'\]/);assert.match(sql,/current_extraction <> p_expected_extraction/);assert.match(sql,/SECURITY INVOKER/);assert.doesNotMatch(sql,/service_role/);});
