import { z } from "zod";
import type { ArtifactStorage, SignedArtifactAccess, StoredArtifact } from "./artifact-storage.ts";
import type { ReportPdfArtifact } from "./report-pdf.ts";
import type { ReportSnapshot } from "./report-versioning.ts";
import type { TenantScope } from "./tenancy.ts";
export const storedGeneratedReportSchema=z.object({reportId:z.string().min(1),assessmentId:z.string().min(1),version:z.number().int().positive(),storageKey:z.string().min(1),checksumSha256:z.string().regex(/^[a-f0-9]{64}$/),mediaType:z.literal("application/pdf"),size:z.number().int().positive(),pageCount:z.number().int().positive(),createdAt:z.string().datetime()}); export type StoredGeneratedReport=z.infer<typeof storedGeneratedReportSchema>; export type GeneratedReportMetadataStore={find(scope:TenantScope,assessmentId:string,reportId:string,accessToken?:string):Promise<StoredGeneratedReport|null>;save(scope:TenantScope,value:StoredGeneratedReport,accessToken?:string):Promise<StoredGeneratedReport>;};
export class GeneratedReportStorageService{
 private readonly objects:ArtifactStorage; private readonly metadata:GeneratedReportMetadataStore;
 constructor(objects:ArtifactStorage,metadata:GeneratedReportMetadataStore){this.objects=objects;this.metadata=metadata;}
 async persist(scope:TenantScope,snapshot:ReportSnapshot,pdf:ReportPdfArtifact,accessToken?:string):Promise<StoredGeneratedReport>{if(snapshot.assessmentId!==snapshot.report.assessmentId)throw new Error("Report snapshot assessment mismatch.");if(pdf.generatedFromDiagnosticAt!==snapshot.generatedFromDiagnosticAt)throw new Error("PDF diagnostic provenance does not match the immutable report snapshot.");const existing=await this.metadata.find(scope,snapshot.assessmentId,snapshot.id,accessToken);if(existing){if(existing.checksumSha256!==pdf.sha256||existing.version!==snapshot.version)throw new Error("Immutable report PDF metadata mismatch.");return existing;}const stored:StoredArtifact=await this.objects.put(scope,snapshot.assessmentId,{originalName:pdf.filename,mediaType:pdf.mediaType,bytes:pdf.bytes,checksumSha256:pdf.sha256});const value=storedGeneratedReportSchema.parse({reportId:snapshot.id,assessmentId:snapshot.assessmentId,version:snapshot.version,storageKey:stored.storageKey,checksumSha256:stored.checksumSha256,mediaType:"application/pdf",size:stored.size,pageCount:pdf.pageCount,createdAt:stored.createdAt});try{return await this.metadata.save(scope,value,accessToken);}catch(error){await this.objects.delete(scope,stored.storageKey).catch(()=>undefined);throw error;}}
 async createSignedReadUrl(scope:TenantScope,value:StoredGeneratedReport):Promise<SignedArtifactAccess|null>{return this.objects.createSignedReadUrl(scope,value.storageKey);} async delete(scope:TenantScope,value:StoredGeneratedReport):Promise<void>{await this.objects.delete(scope,value.storageKey);}}
