import { AUTH_CONFIG, LOCAL_AUTH_CONFIG } from "./config.ts";
import { authenticatedContextSchema, AuthenticationRequiredError, requirePermission, type AuthenticatedContext, type Permission } from "./auth.ts";
import { authenticateProductionSession } from "./production-auth.ts";
import { InvalidSessionError } from "./supabase-auth.ts";
import { getAssessmentRepository, getServerTenantContext } from "./server-assessment-store.ts";
import { scopeFromTenant } from "./tenancy.ts";
function getLocalAuthContext(): AuthenticatedContext { if (!LOCAL_AUTH_CONFIG.enabled) throw new AuthenticationRequiredError(); const tenant = getServerTenantContext(); const scope = scopeFromTenant(tenant); const createdAt = new Date().toISOString(); const user = { id: LOCAL_AUTH_CONFIG.userId, email: LOCAL_AUTH_CONFIG.email, displayName: LOCAL_AUTH_CONFIG.displayName, createdAt }; const membership = getAssessmentRepository().ensureMembership(scope, user, { userId: user.id, organizationId: scope.organizationId, workspaceId: scope.workspaceId, role: LOCAL_AUTH_CONFIG.role, createdAt }); return authenticatedContextSchema.parse({ user, membership, tenant, authMethod: "local-dev", productionReady: false }); }
export function extractAccessToken(request: Request): string { const authorization = request.headers.get("authorization")?.trim(); if (authorization?.toLowerCase().startsWith("bearer ")) { const token = authorization.slice(7).trim(); if (token) return token; } const cookie = request.headers.get("cookie") ?? ""; for (const part of cookie.split(";")) { const [rawName, ...rawValue] = part.trim().split("="); if (rawName === AUTH_CONFIG.accessTokenCookieName) { const value = decodeURIComponent(rawValue.join("=")).trim(); if (value) return value; } } throw new AuthenticationRequiredError(); }
export async function getServerAuthContext(request: Request): Promise<AuthenticatedContext> { if (AUTH_CONFIG.provider === "local") return getLocalAuthContext(); const tenant = getServerTenantContext(); const scope = scopeFromTenant(tenant); const accessToken = extractAccessToken(request); try { return await authenticateProductionSession({ accessToken, tenant, supabase: AUTH_CONFIG.supabase!, resolveMembership: ({ userId }) => getAssessmentRepository().getMembership(scope, userId) }); } catch (error) { if (error instanceof InvalidSessionError) throw new AuthenticationRequiredError(); throw error; } }
export function requireServerPermission(permission: Permission): AuthenticatedContext;
export function requireServerPermission(request: Request, permission: Permission): Promise<AuthenticatedContext>;
export function requireServerPermission(requestOrPermission: Request | Permission, maybePermission?: Permission): AuthenticatedContext | Promise<AuthenticatedContext> { if (typeof requestOrPermission === "string") { if (AUTH_CONFIG.provider !== "local") throw new AuthenticationRequiredError(); return requirePermission(getLocalAuthContext(), requestOrPermission); } return getServerAuthContext(requestOrPermission).then((context) => requirePermission(context, maybePermission!)); }
