import { z } from "zod";
import type { ExtractionReview } from "./extraction-review.ts";
import type { ExtractionEnvelope } from "./extraction.ts";
import { extractionFingerprint, StaleExtractionReviewError, validateReviewAgainstExtraction, type PersistedExtractionReview } from "./review-persistence.ts";
import type { TenantScope } from "./tenancy.ts";
export type SupabaseExtractionReviewConfig = { projectUrl: string; publishableKey: string; timeoutMs: number };
type FetchLike = typeof fetch;
const reviewRowSchema = z.object({ extraction_fingerprint: z.string(), review_json: z.unknown(), updated_at: z.string() });
export class SupabaseExtractionReviewError extends Error { constructor(message = "Managed extraction-review persistence is unavailable.") { super(message); this.name = "SupabaseExtractionReviewError"; } }
function restUrl(config: SupabaseExtractionReviewConfig, path: string) { return `${config.projectUrl.replace(/\/$/, "")}/rest/v1/${path}`; }
async function request(fetchImpl: FetchLike, config: SupabaseExtractionReviewConfig, accessToken: string, path: string, init: RequestInit = {}) { if (!accessToken.trim()) throw new SupabaseExtractionReviewError("A verified Supabase access token is required for managed extraction review."); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), config.timeoutMs); try { const response = await fetchImpl(restUrl(config, path), { ...init, cache: "no-store", signal: controller.signal, headers: { apikey: config.publishableKey, Authorization: `Bearer ${accessToken}`, Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...(init.headers ?? {}) } }); if (!response.ok) { const detail = await response.text().catch(() => ""); if (response.status === 409 || detail.includes("stale extraction")) throw new StaleExtractionReviewError(); throw new SupabaseExtractionReviewError(`Managed extraction-review request failed with status ${response.status}.`); } return response; } catch (error) { if (error instanceof SupabaseExtractionReviewError || error instanceof StaleExtractionReviewError) throw error; throw new SupabaseExtractionReviewError(error instanceof Error && error.name === "AbortError" ? "Managed extraction-review request timed out." : undefined); } finally { clearTimeout(timer); } }
export class SupabaseExtractionReviewStore {
  private readonly config: SupabaseExtractionReviewConfig; private readonly fetchImpl: FetchLike;
  constructor(config: SupabaseExtractionReviewConfig, fetchImpl: FetchLike = fetch) { this.config = config; this.fetchImpl = fetchImpl; }
  async find(accessToken: string, scope: TenantScope, assessmentId: string, extraction: ExtractionEnvelope): Promise<PersistedExtractionReview | null> { const path = `extraction_reviews?select=extraction_fingerprint,review_json,updated_at&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&assessment_id=eq.${encodeURIComponent(assessmentId)}&limit=1`; const response = await request(this.fetchImpl, this.config, accessToken, path); const rows = z.array(reviewRowSchema).parse(await response.json()); if (!rows.length) return null; const row = rows[0]; const review = row.review_json as ExtractionReview; validateReviewAgainstExtraction(review, extraction); return { assessmentId, extractionFingerprint: row.extraction_fingerprint, review, updatedAt: row.updated_at, stale: row.extraction_fingerprint !== extractionFingerprint(extraction) }; }
  async save(accessToken: string, scope: TenantScope, assessmentId: string, extraction: ExtractionEnvelope, review: ExtractionReview, expectedFingerprint: string): Promise<PersistedExtractionReview> { const currentFingerprint = extractionFingerprint(extraction); if (expectedFingerprint !== currentFingerprint) throw new StaleExtractionReviewError(); validateReviewAgainstExtraction(review, extraction); const updatedAt = new Date().toISOString(); await request(this.fetchImpl, this.config, accessToken, "rpc/save_extraction_review", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ p_organization_id: scope.organizationId, p_workspace_id: scope.workspaceId, p_assessment_id: assessmentId, p_expected_extraction: extraction, p_extraction_fingerprint: currentFingerprint, p_review: review, p_updated_at: updatedAt }) }); return { assessmentId, extractionFingerprint: currentFingerprint, review, updatedAt, stale: false }; }
}
