import { z } from "zod";
import { assessmentDraftSchema, type AssessmentDraft } from "./assessment.ts";
import { membershipSchema, type Membership } from "./auth.ts";
import { tenantContextSchema, type TenantContext, type TenantScope } from "./tenancy.ts";
export type SupabasePostgresConfig = { projectUrl: string; publishableKey: string; timeoutMs: number; };
type FetchLike = typeof fetch;
const assessmentRowSchema = z.object({ payload_json: z.unknown() });
const membershipRowSchema = z.object({ user_id: z.string(), organization_id: z.string(), workspace_id: z.string(), role: z.enum(["viewer", "editor", "admin"]), created_at: z.string() });
const tenantRowSchema = z.object({ id: z.string(), name: z.string(), organization_id: z.string(), created_at: z.string(), organizations: z.object({ id: z.string(), name: z.string(), created_at: z.string() }) });
export class SupabasePersistenceError extends Error { constructor(message = "Managed PostgreSQL persistence is unavailable.") { super(message); this.name = "SupabasePersistenceError"; } }
function restUrl(config: SupabasePostgresConfig, path: string) { return `${config.projectUrl.replace(/\/$/, "")}/rest/v1/${path}`; }
async function request(fetchImpl: FetchLike, config: SupabasePostgresConfig, accessToken: string, path: string, init: RequestInit = {}) { if (!accessToken.trim()) throw new SupabasePersistenceError("A verified Supabase access token is required for managed persistence."); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), config.timeoutMs); try { const response = await fetchImpl(restUrl(config, path), { ...init, cache: "no-store", signal: controller.signal, headers: { apikey: config.publishableKey, Authorization: `Bearer ${accessToken}`, Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...(init.headers ?? {}) } }); if (!response.ok) throw new SupabasePersistenceError(`Managed persistence request failed with status ${response.status}.`); return response; } catch (error) { if (error instanceof SupabasePersistenceError) throw error; throw new SupabasePersistenceError(error instanceof Error && error.name === "AbortError" ? "Managed persistence request timed out." : undefined); } finally { clearTimeout(timer); } }
export class SupabasePostgresStore {
  private readonly config: SupabasePostgresConfig;
  private readonly fetchImpl: FetchLike;
  constructor(config: SupabasePostgresConfig, fetchImpl: FetchLike = fetch) { this.config = config; this.fetchImpl = fetchImpl; }
  async resolveMembership(accessToken: string, userId: string, scope: TenantScope): Promise<{ tenant: TenantContext; membership: Membership } | null> { const membershipResponse = await request(this.fetchImpl, this.config, accessToken, `memberships?select=user_id,organization_id,workspace_id,role,created_at&user_id=eq.${encodeURIComponent(userId)}&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&limit=1`); const membershipRows = z.array(membershipRowSchema).parse(await membershipResponse.json()); if (membershipRows.length === 0) return null; const tenantResponse = await request(this.fetchImpl, this.config, accessToken, `workspaces?select=id,name,organization_id,created_at,organizations!inner(id,name,created_at)&id=eq.${encodeURIComponent(scope.workspaceId)}&organization_id=eq.${encodeURIComponent(scope.organizationId)}&limit=1`); const tenantRows = z.array(tenantRowSchema).parse(await tenantResponse.json()); if (tenantRows.length === 0) return null; const row = tenantRows[0]; return { membership: membershipSchema.parse({ userId: membershipRows[0].user_id, organizationId: membershipRows[0].organization_id, workspaceId: membershipRows[0].workspace_id, role: membershipRows[0].role, createdAt: membershipRows[0].created_at }), tenant: tenantContextSchema.parse({ organization: { id: row.organizations.id, name: row.organizations.name, createdAt: row.organizations.created_at }, workspace: { id: row.id, organizationId: row.organization_id, name: row.name, createdAt: row.created_at } }) }; }
  async createAssessment(accessToken: string, scope: TenantScope, assessment: AssessmentDraft): Promise<AssessmentDraft> { const validated = assessmentDraftSchema.parse(assessment); await request(this.fetchImpl, this.config, accessToken, "assessments", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ organization_id: scope.organizationId, workspace_id: scope.workspaceId, id: validated.id, status: validated.status, created_at: validated.createdAt, payload_json: validated }) }); return validated; }
  async findAssessment(accessToken: string, scope: TenantScope, assessmentId: string): Promise<AssessmentDraft | null> { const response = await request(this.fetchImpl, this.config, accessToken, `assessments?select=payload_json&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&id=eq.${encodeURIComponent(assessmentId)}&limit=1`); const rows = z.array(assessmentRowSchema).parse(await response.json()); return rows.length ? assessmentDraftSchema.parse(rows[0].payload_json) : null; }
  async listActiveAssessments(accessToken: string, scope: TenantScope): Promise<AssessmentDraft[]> { const response = await request(this.fetchImpl, this.config, accessToken, `assessments?select=payload_json&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&status=eq.draft&order=created_at.desc`); const rows = z.array(assessmentRowSchema).parse(await response.json()); return rows.map((row) => assessmentDraftSchema.parse(row.payload_json)); }
}
