import { z } from "zod";
import { assessmentDraftSchema, type AssessmentDraft } from "./assessment.ts";
import { membershipSchema, type Membership } from "./auth.ts";
import { tenantContextSchema, type TenantContext, type TenantScope } from "./tenancy.ts";
import type { ParsedArtifact, SourceSegment } from "./artifact-parser.ts";
import type { ExtractionEnvelope } from "./extraction.ts";
import type { ProcessingSnapshot, PersistedArtifactMetadata } from "./processing-repository.ts";
export type SupabasePostgresConfig = { projectUrl: string; publishableKey: string; timeoutMs: number; };
type FetchLike = typeof fetch;
const assessmentRowSchema = z.object({ payload_json: z.unknown() });
const membershipRowSchema = z.object({ user_id: z.string(), organization_id: z.string(), workspace_id: z.string(), role: z.enum(["viewer", "editor", "admin"]), created_at: z.string() });
const tenantRowSchema = z.object({ id: z.string(), name: z.string(), organization_id: z.string(), created_at: z.string(), organizations: z.object({ id: z.string(), name: z.string(), created_at: z.string() }) });
const artifactRowSchema = z.object({ storage_artifact_id: z.string(), parser_artifact_id: z.string(), original_name: z.string(), media_type: z.string(), size_bytes: z.number(), checksum_sha256: z.string(), parser: z.string(), warnings_json: z.array(z.string()), created_at: z.string() });
const segmentRowSchema = z.object({ parser_artifact_id: z.string(), segment_id: z.string(), ordinal: z.number(), kind: z.string(), locator_json: z.record(z.string(), z.unknown()), content: z.string(), content_sha256: z.string(), title: z.string().nullable() });
const extractionSnapshotRowSchema = z.object({ payload_json: z.record(z.string(), z.unknown()), persisted_at: z.string() });
export class SupabasePersistenceError extends Error { constructor(message = "Managed PostgreSQL persistence is unavailable.") { super(message); this.name = "SupabasePersistenceError"; } }
function restUrl(config: SupabasePostgresConfig, path: string) { return `${config.projectUrl.replace(/\/$/, "")}/rest/v1/${path}`; }
async function request(fetchImpl: FetchLike, config: SupabasePostgresConfig, accessToken: string, path: string, init: RequestInit = {}) { if (!accessToken.trim()) throw new SupabasePersistenceError("A verified Supabase access token is required for managed persistence."); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), config.timeoutMs); try { const response = await fetchImpl(restUrl(config, path), { ...init, cache: "no-store", signal: controller.signal, headers: { apikey: config.publishableKey, Authorization: `Bearer ${accessToken}`, Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...(init.headers ?? {}) } }); if (!response.ok) throw new SupabasePersistenceError(`Managed persistence request failed with status ${response.status}.`); return response; } catch (error) { if (error instanceof SupabasePersistenceError) throw error; throw new SupabasePersistenceError(error instanceof Error && error.name === "AbortError" ? "Managed persistence request timed out." : undefined); } finally { clearTimeout(timer); } }
export class SupabasePostgresStore {
  private readonly config: SupabasePostgresConfig;
  private readonly fetchImpl: FetchLike;
  constructor(config: SupabasePostgresConfig, fetchImpl: FetchLike = fetch) { this.config = config; this.fetchImpl = fetchImpl; }
  async resolveMembership(accessToken: string, userId: string, scope: TenantScope): Promise<{ tenant: TenantContext; membership: Membership } | null> { const membershipResponse = await request(this.fetchImpl, this.config, accessToken, `memberships?select=user_id,organization_id,workspace_id,role,created_at&user_id=eq.${encodeURIComponent(userId)}&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&limit=1`); const membershipRows = z.array(membershipRowSchema).parse(await membershipResponse.json()); if (membershipRows.length === 0) return null; const tenantResponse = await request(this.fetchImpl, this.config, accessToken, `workspaces?select=id,name,organization_id,created_at,organizations!inner(id,name,created_at)&id=eq.${encodeURIComponent(scope.workspaceId)}&organization_id=eq.${encodeURIComponent(scope.organizationId)}&limit=1`); const tenantRows = z.array(tenantRowSchema).parse(await tenantResponse.json()); if (tenantRows.length === 0) return null; const row = tenantRows[0]; return { membership: membershipSchema.parse({ userId: membershipRows[0].user_id, organizationId: membershipRows[0].organization_id, workspaceId: membershipRows[0].workspace_id, role: membershipRows[0].role, createdAt: membershipRows[0].created_at }), tenant: tenantContextSchema.parse({ organization: { id: row.organizations.id, name: row.organizations.name, createdAt: row.organizations.created_at }, workspace: { id: row.id, organizationId: row.organization_id, name: row.name, createdAt: row.created_at } }) }; }
  async createAssessment(accessToken: string, scope: TenantScope, assessment: AssessmentDraft): Promise<AssessmentDraft> { const validated = assessmentDraftSchema.parse(assessment); await request(this.fetchImpl, this.config, accessToken, "assessments", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ organization_id: scope.organizationId, workspace_id: scope.workspaceId, id: validated.id, status: validated.status, created_at: validated.createdAt, payload_json: validated }) }); return validated; }
  async findAssessment(accessToken: string, scope: TenantScope, assessmentId: string): Promise<AssessmentDraft | null> { const response = await request(this.fetchImpl, this.config, accessToken, `assessments?select=payload_json&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&id=eq.${encodeURIComponent(assessmentId)}&limit=1`); const rows = z.array(assessmentRowSchema).parse(await response.json()); return rows.length ? assessmentDraftSchema.parse(rows[0].payload_json) : null; }
  async listActiveAssessments(accessToken: string, scope: TenantScope): Promise<AssessmentDraft[]> { const response = await request(this.fetchImpl, this.config, accessToken, `assessments?select=payload_json&organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&status=eq.draft&order=created_at.desc`); const rows = z.array(assessmentRowSchema).parse(await response.json()); return rows.map((row) => assessmentDraftSchema.parse(row.payload_json)); }
  async replaceProcessing(accessToken: string, scope: TenantScope, snapshot: ProcessingSnapshot): Promise<ProcessingSnapshot> { const persistedAt = snapshot.persistedAt || new Date().toISOString(); const segments = snapshot.parsedArtifacts.flatMap((parsed) => parsed.sourceSegments.map((segment) => ({ parser_artifact_id: parsed.artifactId, segment_id: segment.id, ordinal: segment.ordinal, kind: segment.kind, locator_json: segment.locator, content: segment.content, content_sha256: segment.contentSha256, title: segment.title ?? null }))); await request(this.fetchImpl, this.config, accessToken, "rpc/replace_processing_snapshot", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ p_organization_id: scope.organizationId, p_workspace_id: scope.workspaceId, p_assessment_id: snapshot.assessmentId, p_artifacts: snapshot.artifacts.map((artifact) => ({ storage_artifact_id: artifact.storageArtifactId, parser_artifact_id: artifact.parserArtifactId, original_name: artifact.originalName, media_type: artifact.mediaType, size_bytes: artifact.size, checksum_sha256: artifact.checksumSha256, parser: artifact.parser, warnings_json: artifact.warnings, created_at: artifact.createdAt })), p_segments: segments, p_extraction: snapshot.extraction, p_persisted_at: persistedAt }) }); return { ...snapshot, persistedAt }; }
  async findProcessing(accessToken: string, scope: TenantScope, assessmentId: string): Promise<ProcessingSnapshot | null> { const scoped = `organization_id=eq.${encodeURIComponent(scope.organizationId)}&workspace_id=eq.${encodeURIComponent(scope.workspaceId)}&assessment_id=eq.${encodeURIComponent(assessmentId)}`; const extractionResponse = await request(this.fetchImpl, this.config, accessToken, `extraction_snapshots?select=payload_json,persisted_at&${scoped}&limit=1`); const extractionRows = z.array(extractionSnapshotRowSchema).parse(await extractionResponse.json()); if (!extractionRows.length) return null; const [artifactResponse, segmentResponse] = await Promise.all([request(this.fetchImpl, this.config, accessToken, `artifact_metadata?select=storage_artifact_id,parser_artifact_id,original_name,media_type,size_bytes,checksum_sha256,parser,warnings_json,created_at&${scoped}&order=created_at.asc,storage_artifact_id.asc`), request(this.fetchImpl, this.config, accessToken, `source_segments?select=parser_artifact_id,segment_id,ordinal,kind,locator_json,content,content_sha256,title&${scoped}&order=parser_artifact_id.asc,ordinal.asc`)]); const artifactRows = z.array(artifactRowSchema).parse(await artifactResponse.json()); const segmentRows = z.array(segmentRowSchema).parse(await segmentResponse.json()); const artifacts: PersistedArtifactMetadata[] = artifactRows.map((row) => ({ storageArtifactId: row.storage_artifact_id, parserArtifactId: row.parser_artifact_id, originalName: row.original_name, mediaType: row.media_type, size: row.size_bytes, checksumSha256: row.checksum_sha256, parser: row.parser as ParsedArtifact["parser"], warnings: row.warnings_json, createdAt: row.created_at })); const grouped = new Map<string, SourceSegment[]>(); for (const row of segmentRows) { const artifact = artifacts.find((item) => item.parserArtifactId === row.parser_artifact_id); const segment: SourceSegment = { id: row.segment_id, artifactId: row.parser_artifact_id, artifactName: artifact?.originalName ?? "artifact", ordinal: row.ordinal, kind: row.kind as SourceSegment["kind"], locator: row.locator_json as SourceSegment["locator"], content: row.content, contentSha256: row.content_sha256, ...(row.title ? { title: row.title } : {}) }; grouped.set(row.parser_artifact_id, [...(grouped.get(row.parser_artifact_id) ?? []), segment]); } const parsedArtifacts: ParsedArtifact[] = artifacts.map((artifact) => { const sourceSegments = grouped.get(artifact.parserArtifactId) ?? []; return { artifactId: artifact.parserArtifactId, artifactName: artifact.originalName, parser: artifact.parser, sourceSegments, warnings: artifact.warnings, stats: { segmentCount: sourceSegments.length, characterCount: sourceSegments.reduce((sum, segment) => sum + segment.content.length, 0) } }; }); return { assessmentId, artifacts, parsedArtifacts, extraction: extractionRows[0].payload_json as ExtractionEnvelope, persistedAt: extractionRows[0].persisted_at }; }
}
