import { NextResponse } from "next/server";
import { AuthenticationRequiredError, AuthorizationDeniedError } from "@/lib/auth";
import { requireServerPermission } from "@/lib/server-auth";
import { listReportsForRequest, saveReportForRequest } from "@/lib/server-report-access";
import { generateCurrentExecutiveReportForRequest, ReportStateUnavailableError } from "@/lib/server-report-state";
export const runtime = "nodejs";
function authError(error: unknown) { if (error instanceof AuthenticationRequiredError) return NextResponse.json({ error: error.message }, { status: 401 }); if (error instanceof AuthorizationDeniedError) return NextResponse.json({ error: error.message }, { status: 403 }); return null; }
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; try { const auth = await requireServerPermission(request, "report:read"); const history = await listReportsForRequest(request, auth, id); return NextResponse.json({ assessmentId: id, reports: [...history].reverse() }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { const response = authError(error); if (response) return response; if (error instanceof ReportStateUnavailableError) return NextResponse.json({ error: error.message }, { status: 409 }); if (error instanceof Error) return NextResponse.json({ error: error.message }, { status: 400 }); throw error; } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; try { const auth = await requireServerPermission(request, "report:write"); const canonicalReport = await generateCurrentExecutiveReportForRequest(request, auth, id); const snapshot = await saveReportForRequest(request, auth, canonicalReport); return NextResponse.json(snapshot, { status: 201, headers: { "Cache-Control": "no-store" } }); } catch (error) { const response = authError(error); if (response) return response; if (error instanceof ReportStateUnavailableError) return NextResponse.json({ error: error.message }, { status: 409 }); if (error instanceof Error) return NextResponse.json({ error: error.message }, { status: 400 }); throw error; } }
